chore: Remove dev releases
fluttertools/sidekick pull request #310
Opened 2024-02-15 07:55 UTC by defuncart

As the `dev` channel has been deprecated for the last two years or so, doesn't seem to make sense to show it anymore in releases page.

![Bildschirmfoto 2024-02-15 um 08 52 31](https://github.com/fluttertools/sidekick/assets/13286425/32f3f2f1-88ee-4d74-9456-a40ba79f9c60)

2024-02-18 03:53 UTC, aguilaair requested changes
Could this be removed from the translations, too, please? That way we don't have orphaned key:value pairs

2024-02-18 03:54 UTC, aguilaair commented
Thank you for contributing! This makes complete sense to me, if you could just remove the translations from those files I'll merge it :D

2024-02-18 09:33 UTC, defuncart commented
@aguilaair Removed `modules:search.components.devReleases` l10n key.

2024-02-19 15:23 UTC, defuncart commented
@aguilaair CI pipeline is failing due to analyzer warnings with latest stable version. Perhaps fvm version could be set to something older, or migration to latest flutter version in another PR.

2024-02-22 02:28 UTC, aguilaair approved these changes
Looks Good! Let's migrate to the new Flutter version on a different PR :D

2024-02-22 02:28 UTC, merged